/* GENERATED by the site editor on 2026-09-18; stamp:v486fu; hand edits are overwritten */
window.AMH_IMAGES = {"v":2,"stamp":"v486fu","nextImg":"0007","images":[
{"base":"blog/260916_img0006","kind":"image","type":"png","mime":"image/png","from":"","ow":32,"oh":32,"bytes":459,"animated":false,"added":"260916","used":["p0011"],"words":{"p0011":"Satellite · satellitetest"},"num":"0006","date":"260916","uhd":true,"truesize":true},
{"base":"img/work/satellitetest-h9mf0w","kind":"image","type":"png","mime":"image/png","from":"","ow":853,"oh":645,"bytes":367973,"animated":false,"added":"260917","used":["index.html#fr3-gallery","gallery.html#gal-tbg"],"words":{"index.html#fr3-gallery":"Test 123 · satellitetest","gallery.html#gal-tbg":"satellitetest"}},
{"base":"img/work/image-1pbxic","kind":"image","type":"png","mime":"image/png","from":"","ow":32,"oh":32,"bytes":459,"animated":false,"added":"260917","used":["index.html#fr3-gallery"],"words":{"index.html#fr3-gallery":"Icon test · image"}}
]};
