/* GENERATED by the site editor on 2026-09-17; stamp:q7sg08; hand edits are overwritten */
window.AMH_IMAGES = {"v":1,"stamp":"q7sg08","nextImg":"0007","images":[
{"base":"blog/260916_img0006","type":"png","ow":32,"oh":32,"bytes":459,"animated":false,"added":"260916","used":["p0011"],"num":"0006","date":"260916","uhd":false,"truesize":false},
{"base":"img/work/satellitetest-h9mf0w","type":"png","ow":853,"oh":645,"bytes":367973,"animated":false,"added":"260917","used":["index.html#fr3-gallery","gallery.html#gal-tbg"]},
{"base":"img/work/image-1pbxic","type":"png","ow":32,"oh":32,"bytes":459,"animated":false,"added":"260917","used":["index.html#fr3-gallery"]}
]};
