/* GENERATED by the blog.html publish engine on 2026-09-04; stamp:78jsjb; hand edits are overwritten */
window.AMH_SEARCH = "H4sIAAAAAAAACkXOMQ+CMBAF4L9S39yhoEHtrLMLm2Eo0kAJhcY7jJHw380RE8fvvXfJLXjBZhrELiZYHE899TU00kRMsPcFoYGFMeYAjcaxh0VemPNmDlGc7fMCGp9pFF0v5VbxICo9scokcC3BYoqtSoMbPbtnmKMU/s0y7AKpQMoplpNbbEWBf8FO/QdDIIbGwyV5sdLgbo41LLBW6xdlep5K0wAAAA==";
