/* GENERATED by the blog.html publish engine on 2026-09-04; stamp:ugyme3; hand edits are overwritten */
window.AMH_SEARCH = {"v":1,"stamp":"ugyme3","posts":[{"id":"0006","date":"260904","time":"1515","zone":"EDT","title":"asd","tags":"","text":"123asd","caps":[],"thumb":""},{"id":"0007","date":"260904","time":"1656","zone":"EDT","title":"asd","tags":"","text":"123","caps":[],"thumb":""}]};
